# Code generated by Claude 3.7 Sonnet Thinking (Preview) start
import contextlib
from collections.abc import Generator


@contextlib.contextmanager
def lazy_imports(
    *modules: str, extend: bool = False, catchall: bool | None = None
) -> Generator[None, None, None]: ...
# Code generated by Claude 3.7 Sonnet Thinking (Preview) end
